#subfolder: mobilenetV2_hc_sparsity_20_3lam6
trial_num: 1

# Hypercube optimization
algo: 'hc_iter'
iter_period: 5

# Architecture
arch: MobileNetV2

# ===== Dataset ===== #
dataset: CIFAR10
name: mobilenetV2_hc

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.01 #0.01
lr_policy: cosine_lr #constant_lr #multistep_lr
fine_tune_lr: 0.01
fine_tune_lr_policy: multistep_lr

# ===== Network training config ===== #
epochs: 300 #300
wd: 0.0 
momentum: 0.9
batch_size: 128

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_type: BottomK
# enter target sparsity here
target_sparsity: 20.0
unflag_before_finetune: True
init: signed_constant
score_init: unif #skew #half #bimodal #skew # bern
scale_fan: False #True

# ===== Rounding ===== #
round: naive 
noise: True
noise_ratio: 0 

# ===== Quantization ===== #
hc_quantized: True
quantize_threshold: 0.5

# ===== Regularization ===== #
regularization: L2
lmbda: 0.000001

# ===== Hardware setup ===== #
workers: 4
#gpu: 1

# ===== Checkpointing ===== #
checkpoint_at_prune: False

# ==== sanity check ==== #
skip_sanity_checks: True