#subfolder: tiny_hc_sparsity_0_5_adam_1lam5
trial_num: 1


# Hypercube optimization
algo: 'hc_iter'
iter_period: 5

# Architecture
arch: TinyResNet18

# ===== Dataset ===== #
dataset: TinyImageNet
name: tiny_resnet18_hc

# ===== Learning Rate Policy ======== #
optimizer: adam
lr: 0.001
lr_policy: cosine_lr #constant_lr #multistep_lr
fine_tune_lr: 0.1
fine_tune_lr_policy: multistep_lr

# ===== Network training config ===== #
epochs: 200
wd: 0
momentum: 0.9
batch_size: 256 # 256

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_type: BottomK
# enter target sparsity here
target_sparsity: 0.5
unflag_before_finetune: True
init: signed_constant
score_init: unif #skew #half #bimodal #skew # bern
scale_fan: False #True

# ===== Rounding ===== #
round: naive 
noise: True
noise_ratio: 0 

# ===== Quantization ===== #
hc_quantized: True
quantize_threshold: 0.5

# ===== Regularization ===== #
regularization: L2
lmbda: 0.00001

# ===== Hardware setup ===== #
workers: 4
#gpu: 0

# ===== Checkpointing ===== #
checkpoint_at_prune: False

# ==== sanity check ==== #
#skip_sanity_checks: True
