#subfolder: EP_sparsity_1_4
algo: 'ep'
override_prune_rate: True

# Architecture
arch: tinyMobileNetV2

# ===== Dataset ===== #
dataset: TinyImageNet
name: mobileV2_tiny

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr
fine_tune_lr: 0.1
fine_tune_lr_policy: multistep_lr

# ===== Network training config ===== #
epochs: 300 
fine_tune_wd: 0.00004
momentum: 0.9
batch_size: 128 #256

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
init: signed_constant
mode: fan_in
nonlinearity: relu
prune_rate: 0.014
scale_fan: True
freeze_weights: True

# ===== Hardware setup ===== #
workers: 4
#gpu: 0

# ===== Checkpointing ===== #
checkpoint_at_prune: False

# ==== sanity check ==== #
skip_sanity_checks: True
