# IMP algorithm
algo: 'imp'
seed: 42

# Architecture
arch: MobileNetV2

# ===== Dataset ===== #
dataset: CIFAR10

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: multistep_lr
lr_gamma: 0.1

# ===== Network training config ===== #
# epochs: 300
wd: 0.00004
momentum: 0.9
batch_size: 128
bias: False 

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
prune_rate: 0.2
init: kaiming_normal
iter_period: 300 # 5
imp_rewind_iter: 1000


# ===== Hardware setup ===== #
workers: 4
gpu: 2

