# subfolder: sr
algo: 'pt_sr'
#random_subnet: True
#sr_version: 3
# smart_ratio: 0.98 # 2% sparsity

# Architecture
arch: resnet20

# ===== Dataset ===== #
dataset: CIFAR10
name: resnet20_cifar10_sc

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.0000001
lr_policy: cosine_lr
#fine_tune_lr: 0.1
#fine_tune_lr_policy: multistep_lr # cosine_lr
#fine_tune_wd: 0.0001

# ===== Network training config ===== #
epochs: 150 #150
momentum: 0.9
batch_size: 128 # 256

# ===== Sparsity =========== #
conv_type: SubnetConv
bias: False
bn_type: NonAffineBatchNorm
init: signed_constant
mode: fan_in
nonlinearity: relu
scale_fan: False
freeze_weights: True
target_sparsity: 1.44

# ===== Hardware setup ===== #
workers: 4
# gpu: 3

# ===== Checkpointing ===== #
checkpoint_at_prune: False

# ==== sanity check ==== #
skip_sanity_checks: True

# ==== fine-tune ==== #
skip_fine_tune: True


