subfolder: resnet18_sanity

# Hypercube optimization
algo: 'hc_iter'
iter_period: 10

# Architecture
arch: TinyResNet18

# ===== Dataset ===== #
dataset: TinyImageNet
name: tiny_resnet18_sanity

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1 #0.01
lr_policy: cosine_lr #constant_lr #multistep_lr
fine_tune_lr: 0.1
fine_tune_lr_policy: multistep_lr

# ===== Network training config ===== #
epochs: 200
wd: 0.0
momentum: 0.9
batch_size: 256


# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_type: BottomK
# enter target sparsity here
#target_sparsity: 5
# decide if you want to "unflag"
unflag_before_finetune: True
init: signed_constant #signed_constant
score_init: unif #skew #half #bimodal #skew # bern
scale_fan: False #True

# ===== Rounding ===== #
round: naive
noise: True
noise_ratio: 0

# ===== Quantization ===== #
hc_quantized: True
quantize_threshold: 0.5

# ===== Regularization ===== #
regularization: L2
#lmbda: 0 # 1e-6

# ===== Hardware setup ===== #
workers: 4
gpu: 0

# ===== Checkpointing ===== #
checkpoint_at_prune: False

# ==== sanity check ==== #
skip_sanity_checks: True
only_sanity: True
sanity_folder: results/tiny_hc_sparsity_5_adam_8lam6/

#results/tiny_hc_sparsity_50_sgd_lam0_unflag_F/ # Local
