subfolder: resnet50_caltech_weight_training
trial_num: 1
score_init: 'all_one'
bias_lastlayer: True

# algorithm
algo: 'hc_iter'
weight_training: True
transfer_learning: True


# Architecture
arch: ResNet50

# ===== Dataset ===== #
dataset: Caltech101
name: resnet50_caltech101_training

# ===== Learning Rate Policy ======== #
optimizer: adam
lr: 0.0001
lr_policy: multistep_lr #cosine_lr #constant_lr

# ===== Network training config ===== #
epochs: 50 #5
wd: 0
momentum: 0.9
batch_size: 16


# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: AffineBatchNorm #NonAffineBatchNorm
freeze_weights: True
prune_rate: -1
init: kaiming_normal
scale_fan: True

# ===== Hardware setup ===== #
workers: 4
gpu: 0


# ===== Checkpointing ===== #
checkpoint_at_prune: False

# ==== sanity check ==== #
skip_fine_tune: True
skip_sanity_checks: True


