subfolder: resnet50_caltech_weight_training
trial_num: 1


# algorithm
algo: 'hc_iter'
weight_training: True
transfer_learning: True


# Architecture
arch: ResNet50

# ===== Dataset ===== #
dataset: caltech101
name: resnet50_caltech101_training

# ===== Learning Rate Policy ======== #
optimizer: adam
lr: 0.0001
lr_policy: constant_lr #multistep_lr #cosine_lr #constant_lr

# ===== Network training config ===== #
epochs: 5
wd: 0
momentum: 0.9
batch_size: 16


# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: -1
init: kaiming_normal
scale_fan: True

# ===== Hardware setup ===== #
workers: 4
gpu: 0

