subfolder: tiny_res50_weight_training_adam_short
trial_num: 1


# algorithm
algo: 'hc_iter'
weight_training: True

# Architecture
arch: ResNet50

# ===== Dataset ===== #
dataset: TinyImageNet
name: tiny_resnet50_training

# ===== Learning Rate Policy ======== #
optimizer: adam
lr: 0.001
lr_policy: multistep_lr #cosine_lr #constant_lr

# ===== Network training config ===== #
epochs: 100
wd: 0.0001
momentum: 0.9
batch_size: 256


# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: -1
init: kaiming_normal
scale_fan: True

# ===== Hardware setup ===== #
workers: 4
gpu: 0

